### ISSUE TITLE
Hero strength

### ISSUE THREAD

**Issue by Qussayyon** [adipiciu/Travian-scripts#11]
Hi @adipiciu,

As title suggest is it possible to read and include hero strength into troops tooltips, just like hero speed is included?

Thanks in advance.

**Comment by adipiciu** [comment]
I will take a look.

**Comment by adipiciu** [comment]
Added function in the script.

**Comment by Qussayyon** [comment]
How can I activate it?
I do not see it in attack page.
Is it possible to add it to settings page, so we can see info about here, such as strength and speed?

Thanks in advance.

**Comment by adipiciu** [comment]
Added hero strength in attack page.
In the settings page is not useful and there is no need to modify the values manually. You can access the travian hero page to see the strength and speed.

**Comment by Qussayyon** [comment]
It worked, Thank you very much.
