### ISSUE TITLE
train troops doesn't work after travian update

### ISSUE THREAD

**Issue by adipiciu** [adipiciu/Travian-scripts#12]
hello, then develop soldiers and then develop farms. can't be done. it gives an error, can you update please?

_Originally posted by @geses78 in https://github.com/adipiciu/Travian-scripts/issues/4#issuecomment-981049454_

**Comment by adipiciu** [comment]
@geses78  Fixed train troops later in version 1.9.2. Can you confirm if it is working ok now?

**Comment by geses78** [comment]
> @geses78 Daha sonra 1.9.2 sürümünde tren birlikleri düzeltildi. Şimdi çalışıp çalışmadığını onaylayabilir misiniz?

evet şuan çalışıyor ellerine sağlık güzel olmuş
