### ISSUE TITLE
Repetitive tasks (ex. farming) not working

### ISSUE THREAD

**Issue by Montyxxx** [adipiciu/Travian-scripts#15]
Hi adipiciu!

I have installed the latest version of your TTQ script (1.9.2). I tried to setup the repetitive troop sending option (like, every minute) on a trial account without Gold Club. Script sends successfully the first attack, but does not repeat attack a minute later - the task is marked as completed and no longer active. I also checked this with the Gold Club on some older versions (1.7.3) back in the days, and the script also failed to perform repetitive tasks. Can you please suggest the solution?

**Comment by adipiciu** [comment]
The script does not have repetitive tasks. If you want to add multiple send troops tasks, you can add a list:
![image](https://user-images.githubusercontent.com/13155063/148905315-3317e533-0f74-480d-a5e7-ae35ce7a8a0f.png)

**Comment by Montyxxx** [comment]
Is it possible to implement repetitive tasks function?

Also, how can I delete all or a group of tasks at once?

**Comment by adipiciu** [comment]
> Is it possible to implement repetitive tasks function?

I don't have any plans on adding new features.

> Also, how can I delete all or a group of tasks at once?

There is no group. You need to remove them one by one. Currently there is no button to delete all tasks.

**Comment by geses78** [comment]
merhaba iyi çalışmalar bende asker destek dönderme ve asker yetiştirmeler çalışmıyor.güncelleme yapabilirmisiniz.

**Comment by geses78** [comment]
iyi günler sonra asker geliştirme ve sonra asker gönder çalışmıyor bi güncelleme yaparmısınız.

**Comment by adipiciu** [comment]
> iyi günler sonra asker geliştirme ve sonra asker gönder çalışmıyor bi güncelleme yaparmısınız.

Update the scripts, the issue is fixed: 
TTQ: 3.9.8
ResourceBar: 2.22.13

**Comment by geses78** [comment]
merhab kolay gelsin iyi günler hastane içinde sonradan yetiştir ve sonradan
iyileştir yapabilirmisiniz.çalışmalatınız çok güzel sizi tebrik
ediyorum.her köy için asker kaçır yapmak mümkün mü?

adipiciu ***@***.***>, 2 Oca 2023 Pzt, 10:28 tarihinde şunu
yazdı:
