### ISSUE TITLE
Broken on new server: ts109.x10.international.travian.com

### ISSUE THREAD

**Issue by Qussayyon** [adipiciu/Travian-scripts#18]
**Script Name**
Example: Travian Resource Bar Plus and Travian Task Queue

**Server address**
Example: ts109.x10.international.travian.com

**User script manager**
Example: Tampermonkey

**Operating System**
Example: Ubuntu 21.04, Android 11

**Describe the bug**
Nothing appear, I think they changed the name of some tags in the page so the whole script is crashing.

**To Reproduce**
default run.

**Expected behavior**
To show resources bar.

**Additional context**
The server is new and it's called Hero fashion test.

**Comment by adipiciu** [comment]
I can't create a new account on that server. It seems it is a test server.

**Comment by Qussayyon** [comment]
may I have ur email, how can I contact U?

**Comment by adipiciu** [comment]
> I can't create a new account on that server. It seems it is a test server.

You have me on skype, adipiciu.

**Comment by geses78** [comment]
sonra asker gönderme ve sıralı asker gönderme çalışmıyor

**Comment by Qussayyon** [comment]
> > I can't create a new account on that server. It seems it is a test server.
> 
> You have me on skype, adipiciu.

Done, I sent U the info to try out.

**Comment by adipiciu** [comment]
Fixed resource bar script. They changed the player profile page.

**Comment by adipiciu** [comment]
> merhaba kolay gelsin evet 2-3 gündür sonra asker göndeme ve sıralı asker gönderme çalışmıyor.bu hatayı düzelte bilirmisiniz.teşekkürler

Fixed send troops later.

**Comment by geses78** [comment]
kolay gelsin dostum.sıralı asker gönderme hala çalışmıyor.onuda
düzeltimisin rica etsem

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virüs
bulunmuyor. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

adipiciu ***@***.***>, 4 May 2022 Çar, 22:27 tarihinde şunu
yazdı:

**Comment by adipiciu** [comment]
> 2.22.1 was working but right now it seems server was upgraded with bug fixes and it doesn't work anymore..

Travian updated the servers again. They removed a lot of information from the webpage.
Try the new script version 2.22.2 and let me know if it works. Make a new topic if you find things that aren't working ok.
