### ISSUE TITLE
Wave builder not working on ts31.x3.europe.travian.com server

### ISSUE THREAD

**Issue by Kongolan** [adipiciu/Travian-scripts#19]
**Script Name**
Travian Wave Builder

**Server address**
ts31.x3.europe.travian.com

**User script manager**
Tampermonkey

**Operating System**
Windows 10

**Describe the bug**
Wave builder is not working at all. At least it doesn't show at the build.php page aka troop sending site. So it's not function right?

**To Reproduce**
1. Install Wave Builder
2. Go to troop sending
3. Nothing shown

**Expected behavior**
I remember it was shown on the bottom of the site?

**Comment by adipiciu** [comment]
I am working on it.
