### ISSUE TITLE
nothing shown

### ISSUE THREAD

**Issue by FMZreto** [adipiciu/Travian-scripts#2]
TTQ v 1.8.7 shows only small button without options (i.e. choose tribe, etc.) and the "build later" or task schedule is not to be found.

![image](https://user-images.githubusercontent.com/89779695/131404688-4dfb41d8-b165-4dff-b790-f835775be0ee.png)

Resource bar plus v 2.21.19 show nothing, except that button after first village.

**Comment by FMZreto** [comment]
fyi

for the server prior to latest rolling out, both script work just perfectly.
![image](https://user-images.githubusercontent.com/89779695/131406088-82b9d1a9-ca56-40aa-a662-9d538d59e72d.png)

**Comment by adipiciu** [comment]
Hmm... I have just created an account on one server with the update and I have only 1 village. Maybe something is different for 2 or more villages.

**Comment by FMZreto** [comment]
> 
> 
> Hmm... I have just created an account on one server with the update and I have only 1 village. Maybe something is different for 2 or more villages.

i can set you as sitter if you want. i'm on international 7

**Comment by FMZreto** [comment]
since the update is allowing us to move the order of village list freely. this may be the issue here.

![image](https://user-images.githubusercontent.com/89779695/131408591-6eee49fe-e3ef-4021-bdc9-5d6250d0abf0.png)

![image](https://user-images.githubusercontent.com/89779695/131408539-05ae6ed4-caa7-4323-a6e5-48e0ee9ff385.png)

**Comment by adipiciu** [comment]
Fixed
