### ISSUE TITLE
Travian Resource Bar Plus works on sittered but not on main account

### ISSUE THREAD

**Issue by sfilatino33** [adipiciu/Travian-scripts#20]
**Script Name**
Travian Resource Bar Plus 

**Server address**
Example: ts21.x2.europe.travian.com

**User script manager**
Tampermonkey 

**Operating System**
Windows 10

** browser**
Opera last version

**Describe the bug**
On opening account TRBP doesnt work ( tamper show it is loaded, but no script windows or script page ehances).
this bug is not present on opening travian with sittered accounts.

1. log in 
2. script correctly loaded
3. no script windows or script on page
4. log out
5. log in on sitter acounts
6. script loader correclty and working

This issue appared about one week, on last upgrade of TRBP and Opera upgrade

**Comment by adipiciu** [comment]
what script version you have?
ts21.x2.europe.travian.com server does not exists

**Comment by sfilatino33** [comment]
hi,
version is 2.22.1 and im sorry, neme server was wrong, 
its ts20.x2.europe.travian.com

**Comment by sfilatino33** [comment]
from main account:
https://ibb.co/VHJDktG
tampermonkey is active and script loaded, but nothing on page

this is sitter situation, script on and page ehancement active
https://ibb.co/7WDY14F

**Comment by adipiciu** [comment]
Travian removed a lot of information from the webpage...
Try the script update 2.22.2 and let me know if it works.

**Comment by sfilatino33** [comment]
hi, now is workin, both on principal and sittered account.
TY 😁
