### ISSUE TITLE
Travian wave  -- He send only 4 and nothing more, i gave 12 in... and just 4 are send. i use firefox. 

### ISSUE THREAD

**Issue by Immortals2022** [adipiciu/Travian-scripts#21]
**Script Name**
Example: Travian Resource Bar Plus or Travian Task Queue or Travian Wave Builder

**Server address**
Example: ts31.x3.europe.travian.com

**User script manager**
Example: Tampermonkey, Violentmonkey, Greasemonkey, Userscripts

**Operating System**
Example: Windows 10, Android 9, iOS 14

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by adipiciu** [comment]
Can you try to send 12 waves manually? I need to see if travian blocks more than 4 waves, so it forces you to use their paid wave builder.

**Comment by adipiciu** [comment]
I just tested sending 8 waves manually. Opened 8 tabs, press send on all 8 tabs. Only 4 attacks are sent.
This means travian disabled sending more than 4 waves manually. 
Wow, just wow.... They are enforcing to use their own wave builder.

I think the script can be modified to send more than 8 waves, but maybe they can detect it was not sent with their own wave builder.

**Comment by Qussayyon** [comment]
> I just tested sending 8 waves manually. Opened 8 tabs, press send on all 8 tabs. Only 4 attacks are sent. This means travian disabled sending more than 4 waves manually. Wow, just wow.... They are enforcing to use their own wave builder.
> 
> I think the script can be modified to send more than 8 waves, but maybe they can detect it was not sent with their own wave builder.

Yup, they must force us to use their own "wave builder", it's normal, it's how they get their money :moneybag:, still the scripts make the game playable, if there was no script I'll stop playing the game.

**Comment by adipiciu** [comment]
I can clone their wave builder method, but if the script will use their wave builder method, and you didn't buy it, it can detect you are using a script to mimic the behavior.

Users will need to report this bug to travian, because you can't send more than 4 waves manually.

**Comment by adipiciu** [comment]
Will be fixed in this week travian update.
https://blog.travian.com/2022/06/changelog-release-1598/
