### ISSUE TITLE
Sending farmlist as scheduled task doesn't work anymore after Release 1598

### ISSUE THREAD

**Issue by justchillin12345** [adipiciu/Travian-scripts#23]
**Script Name**
Travian Task Queue

**Server address**
schild.x1.travian.com

**User script manager**
Tampermonkey

**Operating System**
Google ChromeOS, Version 102.0.5005.125 (Official Build) (64-bit)

**Describe the bug**
After [this release](https://blog.travian.com/2022/06/changelog-release-1598/) was implemented on this server, scheduled farming no longer works:
![Screenshot 2022-06-23 22 16 52](https://user-images.githubusercontent.com/108095796/175474342-61361aba-e01e-4222-85ca-70b1a060b894.png)

**To Reproduce**
Just schedule a farmlist. 

**Expected behavior**
I expect it work as before ;)

**Comment by adipiciu** [comment]
I am working on this. I will update the script later.

**Comment by justchillin12345** [comment]
> I am working on this. I will update the script later.

I got banned now, could it because of this new relaese?

**Comment by adipiciu** [comment]
It is possible they detect wrong server requests.

**Comment by Qussayyon** [comment]
> > I am working on this. I will update the script later.
> 
> I got banned now, could it because of this new relaese?

You better avoid using these automating scripts, because it's easily detectable.

**Comment by justchillin12345** [comment]
> It is possible they detect wrong server requests.

That explains it, I had a lot of those. 

[featurerequest] Script should turn itself off after bad server request. ;)

**Comment by adipiciu** [comment]
Actually it didn't send wrong requests, it just failed before sending the request. The ban is suspicious.

**Comment by adipiciu** [comment]
Fixed send troops and farm lists later.

**Comment by justchillin12345** [comment]
> Actually it didn't send wrong requests, it just failed before sending the request. The ban is suspicious.

So why did it happen?
