### ISSUE TITLE
Spartans

### ISSUE THREAD

**Issue by WendelTytan** [adipiciu/Travian-scripts#24]
upgrade to the new tribe, the Spartans :)

name	atk	Def Inf	Def Cav	speed	bounty	wood	clay	iron	crop	Total	maintenance	Tempo	type
Hoplite 	50	35	30	6	60	110	185	110	35	440	1	00:28:20	inf
Sentinel 	0	40	22	9	0	185	150	35	75	445	1	00:20:32	inf
Shieldsman 	40	85	45	8	40	145	95	245	45	530	1	00:32:16	inf
Twinsteel Therion 	90	55	40	6	50	130	200	400	65	795	1	00:35:12	inf
Elpida Rider 	55	120	90	16	110	555	445	330	110	1440	2	00:46:56	cav
Corinthian Crusher 	195	80	75	9	80	660	495	995	165	2315	3	00:57:12	cav
Ram 	65	30	80	4	0	525	260	790	130	1705	3	01:17:00	ram
Ballista 	50	60	10	3	0	550	1240	825	135	2750	6	02:45:00	ballista
Ephor 	40	60	40	4	0	33450	30665	36240	13935	114290	4	21:32:30	chief
Settler	10	80	80	5	3000	5115	5580	6045	3255	19995	1	09:28:20	settler

there are their numbers, updated to today's date, separated by tabs

[spartans.xlsx](https://github.com/adipiciu/Travian-scripts/files/9329302/spartans.xlsx)

**Comment by adipiciu** [comment]
Hi, the problem is I need to differentiate between servers with spartan tribe and servers without spartan tribe. For now there is only a closed beta server and I don't have an account there.

**Comment by adipiciu** [comment]
> upgrade to the new tribe, the Spartans :)
> 
 Check the new script version. I have added the Spartan tribe, but I still need the resources cost for the Spartan Wall and Asclepeion buildings. Can you post them? And please report if there are other bugs.
