### ISSUE TITLE
troops in resource bar plus not working

### ISSUE THREAD

**Issue by totinaster** [adipiciu/Travian-scripts#28]
**Script Name**
Travian Resource Bar Plus

**Server address**
https://gos.x2.international.travian.com

**User script manager**
Tampermonkey

**Operating System**
Example: Windows 10

**Describe the bug**
when I click on troops in resource bar, everything freeze, it is not possible to click anywhere else, I have to close tab and open again 
![image](https://user-images.githubusercontent.com/54626756/198646080-b4dbf49e-8a14-487a-b93f-975d8eec011d.png)

**Expected behavior**

**Additional context**

**Comment by adipiciu** [comment]
Seems to happen only with Spartan troops. I will fix it in the next update.

**Comment by totinaster** [comment]
Hi, not only with Spartan. I can try every nation, if needed.

Best Regards


Val T


Sent with a Spark

**Comment by adipiciu** [comment]
Fixed.

**Comment by totinaster** [comment]
waw, perfect 👍 🥇 
I want to be so excelent in js as you are @adipiciu
