### ISSUE TITLE
Villages list are gone

### ISSUE THREAD

**Issue by Immortals2022** [adipiciu/Travian-scripts#29]
**Script Name**
Example: Travian Resource Bar Plus or Travian Task Queue or Travian Wave Builder
Resources
**Server address**
[Example: ts31.x3.europe.travian.com]
https://ts39.x3.international.travian.com

**User script manager**
Example: Tampermonkey, Violentmonkey, Greasemonkey, Userscripts
Greasemonkey
**Operating System**
Example: Windows 10, Android 9, iOS 14
Win 10
**Describe the bug**
When i want to send some resources to a other village, the villages are not there its only with the send resources button
https://prnt.sc/bUwNzGYOjIhP   see the link
**To Reproduce**

**Expected behavior**
I hope you can fix this. 
**Additional context**

**Comment by adipiciu** [comment]
I don't have an account on the test PTR server. 
It seems they are preparing a big update:
[](https://blog.travian.com/2022/11/quality-of-life-changes-parallel-sessions-for-duals-and-sitters-oases-changes-and-much-more/)
