### ISSUE TITLE
The script no longer displays the optimal number of units to loot when scouting

### ISSUE THREAD

**Issue by ChoLee911** [adipiciu/Travian-scripts#30]
**Script Name**
Example: Travian Resource Bar Plus or Travian Task Queue or Travian Wave Builder

**Server address**
Example: ts31.x3.europe.travian.com

**User script manager**
Example: Tampermonkey, Violentmonkey, Greasemonkey, Userscripts

**Operating System**
Example: Windows 10, Android 9, iOS 14

**Describe the bug**
The script no longer displays the optimal number of units to loot when scouting

**To Reproduce**
1. Go to 'report'
2. Click on 'mouseover resource'
![Screenshot](https://user-images.githubusercontent.com/119853465/205612429-a6f2c5a1-2be9-4f5b-8596-3ca1fb3aa587.png)

**Expected behavior**

**Additional context**

**Comment by adipiciu** [comment]
I will update the script in a few days, after travian update all the servers.

**Comment by ChoLee911** [comment]
> I will update the script in a few days, after travian update all the servers.

you are the best guy ever!

**Comment by adipiciu** [comment]
Fixed
