### ISSUE TITLE
Travian Task Queue stops running

### ISSUE THREAD

**Issue by jrms2** [adipiciu/Travian-scripts#32]
**Script Name**
  Travian Task Queue 

**Server address**
 ts31.x3.europe.travian.com](https://ts31.x3.international.travian.com

**User script manager**
Tampermonkey

**Operating System**
Windows 10 22H2 SO19045.2364

**Describe the bug**
While we change between resources and buildings, task list dissappears, seems the script stop running. Also if we set up task's they run normally like FarmList, but sometimes when you just refresh your page seems the script going inactive. Grey bar in top right corner of screen instead of white.

**To Reproduce**
Hard to tell, only when you refresh page or updates sometimes the bot script stops, if you change between resources or open barracks sometimes the scrips comes back others you need to go statistics or map 

**Expected behavior**
Scrip keep always running no matter your refresh page.

**Additional context**
https://prnt.sc/qyZgJlRzZ40O
https://prnt.sc/JENY86FbyTkG
https://prnt.sc/eFsi0SJSepw-

**Comment by adipiciu** [comment]
You have 2 different versions of the script installed. Go to Tampermonkey - Dashboard and remove the old one.

**Comment by adipiciu** [comment]
The latest version is 2.0.1. Where do you got the 2.4.5 version?
