### ISSUE TITLE
new market doesn't work anymore could you update pls?

### ISSUE THREAD

**Issue by cheryiit** [adipiciu/Travian-scripts#34]
**Script Name**
Example: Travian Resource Bar Plus 

**Server address**
https://alpler.x3.turkey.travian.com/

**User script manager**
Tampermonkey

**Operating System**
 Windows 11

**Describe the bug**
new market interface.
https://www.linkpicture.com/q/Ekran-goruntusu-2023-03-17-145618.png

**Comment by cheryiit** [comment]
hey buddy i cant understan there is a lot of thing could you update pls?

**Comment by adipiciu** [comment]
@cheryiit Hi, I don't have an account anymore. I need to make an account first where I can send resources.

**Comment by adipiciu** [comment]
Fixed the send resources links. 

Next, I will update the market summary next and the memory button. It's really a big change, some of the script functions were included in the game and the interface doesn't have too much space for the script extra buttons.

**Comment by adipiciu** [comment]
@cheryiit I didn't had too much time, but I am working on this. The M(memory) button is almost finished.
But there are some travian bugs, the market popup opens if you change the village, the duration time is not updated if you change coordinates. I can't fix these problems. It's like they didn't tested enough and rush to add that market popup abomination.

**Comment by cheryiit** [comment]
i think because of the mobile app.

**Comment by cheryiit** [comment]
hey buddy i want to also i need to use/test it can i?

**Comment by akyag** [comment]
I really hope they reverse the current state of market. This was definitely not thought through. Adds so many clicks if you need to put multiple offers in market than the previous design.

**Comment by adipiciu** [comment]
Added basic M(emory) button on market. Not fully functional. Only autocompletes resources needed. Village coordinates are not updated. The resources in the memory are not cleared after sending.

**Comment by cheryiit** [comment]
i cant see where is it the paste Memory button.

**Comment by cheryiit** [comment]
i saw but you need to change button code like this to this:
<button class="textButtonV2 buttonFramed send disabled rectangle withText green" type="submit" title=""><div>Send resources</div></button>

to:

<button class="textButtonV2 buttonFramed send rectangle withText green"

**Comment by adipiciu** [comment]
It works only on Firefox + Greasemonkey for the moment.

**Comment by adipiciu** [comment]
Added market summary and overflow.

**Comment by adipiciu** [comment]
Major update after a long investigation. Fixed the M(emomry) button in Tampermonkey and Violentmonkey. Check new script version 2.23.6.
Still need to add %(percent fill) and other missing buttons in market.

**Comment by cheryiit** [comment]
thanx sir works perfectly

**Comment by adipiciu** [comment]
Added equal/percent/clear buttons.

**Comment by adipiciu** [comment]
Added resource selection checkboxes in market

**Comment by adipiciu** [comment]
Added plus/minus all resources buttons
