### ISSUE TITLE
M+

### ISSUE THREAD

**Issue by EmptySD** [adipiciu/Travian-scripts#35]
Is there a way to make an input in new market place? I tried the following:
val, focus+input, trigger: keydown, keypress, keyup, change, text, textInput, ajax post directly to send script, different headers, etc. Nothing seams to work.

**Comment by adipiciu** [comment]
They added some script functions in the game. I still need to add the market summary back and the memory button at least. But it will take some time.

**Comment by adipiciu** [comment]
Added basic M(emory) button on market. Not fully functional. Only autocompletes resources needed. Village coordinates are not updated. The resources in the memory are not cleared after sending.

**Comment by EmptySD** [comment]
> It does not work because extensions are isolated from the page events. You can simulate or break the isolation, but another problem is that travian sends server requests to validate the coordinates. Travian can catch bots and scripts if they validate both X and Y fields in a short time.

Why do you fill XY when it will automatically take it from parameters URL and it will act as send resource towards that village is clicked. Ether by x=&y= or by village map id. Add me on discord please: EmptySD#3986

**Comment by adipiciu** [comment]
Because the M function will refresh the page if it's using the url coordinates.

**Comment by adipiciu** [comment]
Fixed in 2.23.6
