### ISSUE TITLE
Unable to send hero for send later when hero is away

### ISSUE THREAD

**Issue by nathnet** [adipiciu/Travian-scripts#37]
**Script Name**
Travian Task Queue

**Server address**
Example: ts6.x1.asia.travian.com

**User script manager**
Tampermonkey

**Operating System**
Windows 10

**Describe the bug**
Choosing hero for send later resulted in sending Equites Caesaris instead

**To Reproduce**
1. Go to 'Rally point' send troops page
2. Add hero when the hero is away
3. Click send later
4. See error shown as [Equites Caesaris]: 1 being chosen instead of the hero

**Expected behavior**
Choosing hero for send later should queue the hero for sending

**Comment by adipiciu** [comment]
Added the pull request + fixed other functions (research later, party later).
