### ISSUE TITLE
Search option only for oases and filter for animals.

### ISSUE THREAD

**Issue by avarishd** [adipiciu/Travian-scripts#39]
**Script Name**
Travian Resource Bar Plus

**Is your feature request related to a problem? Please describe.**
Currently, if you search via neighbors (with or without the query for animals info in oases) you are given the list of all tiles that contain players and oases.

**Describe the solution you'd like**
New option to search only oases or players, and a filter for animals, when searching for oases.

**Describe alternatives you've considered**
Split neighbors into 2 queries - Players & Oases (with the animal info option being only available to oases)

**Comment by adipiciu** [comment]
The server returns oases and villages, so that is why it was not separated. Also you can see what oases are occupied by players, so it makes sense to include occupied oases as well. Maybe adding a filter is possible, but I don't see many players needing this.
