### ISSUE TITLE
Marksman speed

### ISSUE THREAD

**Issue by FMZreto** [adipiciu/Travian-scripts#41]
**Script Name** : Travian Resource Bar Plus

**Describe the bug**
This is not quite a bug but a little issue about the speed of marksman of Huns is not consistent in the game.
The velocity should be 15 fields/hour for x1 speed server.
I usually edit the code myself but I think it is worth mention here so this script could be even better. 

Thank you for your good work.

**Comment by adipiciu** [comment]
Currently the troops info appears in 3 location in the script and was not updated everywhere.
I will check again, maybe other troops data is old, because they modified some values in the last 2 years.

**Comment by adipiciu** [comment]
Updated Marksman speed also in the all troops speed table.
