### ISSUE TITLE
not working more for wave builder,,please solve it

### ISSUE THREAD

**Issue by oktaviaarma** [adipiciu/Travian-scripts#44]
**Script Name**
Example: Travian Resource Bar Plus or Travian Task Queue or Travian Wave Builder

**Server address**
Example: ts31.x3.europe.travian.com

**User script manager**
Example: Tampermonkey, Violentmonkey, Greasemonkey, Userscripts

**Operating System**
Example: Windows 10, Android 9, iOS 14

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by kokoska222** [comment]
after the last update a few days ago, everything went wrong and wawe builder doesn't work

**Comment by adipiciu** [comment]
Fixed. Thanks @xinyin025

 #43

**Comment by kokoska222** [comment]
I thank you very much
