### ISSUE TITLE
wave builder start no waves

### ISSUE THREAD

**Issue by maxmuster001** [adipiciu/Travian-scripts#46]
**Script Name**
Example: Travian Resource Bar Plus or Travian Task Queue or Travian Wave Builder

**Server address**
Example: ts31.x3.europe.travian.com

**User script manager**
Example: Tampermonkey, Violentmonkey, Greasemonkey, Userscripts

**Operating System**
Example: Windows 10, Android 9, iOS 14

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by adipiciu** [comment]
Wave builder works ok. What server are you playing?

**Comment by kikuman** [comment]
Wave builder works fine for me too. But a send later feature for waves would be nice too.

**Comment by maxmuster001** [comment]
https://sow.x1.america.travian.com/

**Comment by adipiciu** [comment]
> https://sow.x1.america.travian.com/
> 
> hi send only one wave

You need to add more waves. Are you sure you are doing it right?

**Comment by maxmuster001** [comment]
yes, in older Travian Versions, i have sent 8 waves. This is the new special Version. 
**Shores of War**

**Comment by adipiciu** [comment]
I have only a test account and I can test only raid attacks.
Can you confirm if raid attacks work ok?

**Comment by adipiciu** [comment]
If you have a test account, you can write me on telegram: adipiciu

**Comment by maxmuster001** [comment]
Raid attacks also only sent one wave

**Comment by adipiciu** [comment]
I just tested raid attacks on sow.x1.america.travian.com and they work ok. Normal attacks without catapults also work ok.
Try with another account, or with another browser.

**Comment by adipiciu** [comment]
I just tested raid attacks on sow.x1.america.travian.com and they work ok. Normal attacks without catapults also work ok.
Try with another account, or with another browser.

**Comment by raedzzzz** [comment]
hello can i contact you please ? i need you to do for me a script , and sure i will pay for it if you want

**Comment by adipiciu** [comment]
I think I know the problem. It automatically selects "use ships" and if you have only one ship it sends only one wave.

> Raid attacks also only sent one wave

**Comment by adipiciu** [comment]
Fixed in version 2.9
