### ISSUE TITLE
Send Later button disappear

### ISSUE THREAD

**Issue by FMZreto** [adipiciu/Travian-scripts#5]
Send Troops Functions for every villages, except the top, is unusable.

This is for the first village
![image](https://user-images.githubusercontent.com/89779695/134950450-75ab23a0-28dc-431d-9dc7-c233c5403be2.png)

and this is for others
![image](https://user-images.githubusercontent.com/89779695/134950556-4ac63466-dcef-4a6b-b37a-34296e0ef3fd.png)

**Comment by adipiciu** [comment]
Another Travian update is in progress
![image](https://user-images.githubusercontent.com/13155063/134951146-f1975672-94a8-4e2b-a457-80badf51bcc7.png)
I will update the script in the next days

**Comment by adipiciu** [comment]
I still can't reproduce the bug after the update.

**Comment by adipiciu** [comment]
Press F12 in Chrome and go to console tab, maybe there is other error on that page. Something is different on that specific village.

**Comment by geses78** [comment]
merhaba bende de daha sonra geliştir ve daha sonra asker gönder.kayıt ediyorum ama çalışmıyor.bir güncelleme yaparsanız sevinirim.

**Comment by geses78** [comment]
merhaba sonra asker yetiştir çalışmıyor.

**Comment by geses78** [comment]
sonra asker bas diyorum çıkmıyor.sonra asker basma çalışmıyor
