### ISSUE TITLE
Market incoming summary disappears

### ISSUE THREAD

**Issue by kikuman** [adipiciu/Travian-scripts#50]
Travian Resource Bar Plus 2.23.15
Violentmonkey
Windows 10

When there are many incoming market transports a Show All button appears
![Screenshot 2023-11-25 020844](https://github.com/adipiciu/Travian-scripts/assets/5669436/ab6240ee-bd57-4112-a418-758b874c2dfd)
but after clicking it, the summary info disappears.

**Comment by adipiciu** [comment]
How many transports?

**Comment by kikuman** [comment]
10+

**Comment by adipiciu** [comment]
Check script version 2.23.20

**Comment by kikuman** [comment]
> Check script version 2.23.20

fixed!, thx!
