### ISSUE TITLE
button missing

### ISSUE THREAD

**Issue by FlorinSitar** [adipiciu/Travian-scripts#51]
**Script Name**
Example: Travian Task Queue 

**Server address**
Example: [ts31.x3.europe.travian.com]

**User script manager**
Example: Tampermonkey

**Operating System**
Example: Windows 10

**Describe the bug**
The send button in farm list has disappear.

**Expected behavior**
the neew update hides the button.

**Additional context**
Good script! thx a lot!

**Comment by adipiciu** [comment]
Travian changed the farm lists code.

**Comment by adipiciu** [comment]
I have updated the script. If the farmlists are expanded, it will skip farms with casualties.
