### ISSUE TITLE
Find animals in the oases of a farm list no longer works after the new Travian update

### ISSUE THREAD

**Issue by daniel3303** [adipiciu/Travian-scripts#52]
**Script Name**
Travian Resource Bar Plus

**Server address**
lusobr.x1.lusobrasileiro.travian.com

**User script manager**
Tampermonkey

**Operating System**
Windows 11

**Describe the bug**
The feature of searching for animals in the farm list no longer works. Actually the buttons don't even appear after the new Travian update.

**Comment by adipiciu** [comment]
It seems the new farm list automatically de-activates farms if there are losses.

**Comment by adipiciu** [comment]
Added in version 2.23.22
