### ISSUE TITLE
Unknown town

### ISSUE THREAD

**Issue by Poulpi76** [adipiciu/Travian-scripts#53]
Travian Task Queue

ts7.x1.europe.travian.com

Violentmonkey

Windows 10

TTQ doesn't work with farm list (oasis)

message error: 
Unknown town
May have not happened ! was attempted but failed.
Reason : (timeout or TTQ crash)

**Comment by adipiciu** [comment]
What TTQ version? 
Click on TTQ script menu and select Reset. Try again and let me know if it works.

**Comment by Toupak76** [comment]
It's the last update 2.0.7
I have reset many times. it doesn't work

**Comment by adipiciu** [comment]
I need more details. I don't understand exactly when the issue happens.
Send farm list later doesn't work only for farm lists with oasis in them? Because the script doesn't check what farms are in the lists...

**Comment by Toupak76** [comment]
Send later works for everything... except farm list no matter what it contains (oasis or village)
every time I get the error message : unknown town

**Comment by adipiciu** [comment]
I have added a Debug option in the menu in TTQ 2.0.8. Please set Debug to 3 and send the logs from the screen.

**Comment by Toupak76** [comment]
I have retry again with new update... now that works !

**Comment by Toupak76** [comment]
oh finally not... sometimes yes, sometimes no :D

**Comment by adipiciu** [comment]
I have updated the script with some more logging. Can you set Debug to 3 and send me the logs from the screen?

**Comment by Poulpi76** [comment]
Can I send this to you privately?

**Comment by adipiciu** [comment]
> Can I send this to you privately?

Yes. adipiciu on skype or telegram.

**Comment by Poulpi76** [comment]
Done on skype

**Comment by adipiciu** [comment]
Fixed in version TTQ 2.0.10. The issue appeared only when farmlist were expanded and the farm was not raided before.
