### ISSUE TITLE
Farm list properties 

### ISSUE THREAD

**Issue by Drshammasi** [adipiciu/Travian-scripts#55]
*Script Name:
Travian Resource Bar Plus 

*Feature request:
There use to be a feature  in the old versions. Last time I used was on T3.6-T4
when you go to the farm list bellow each list, there would show check-boxes for:
losses (yellow-red-green), loot (full loot - some loot - no loot) and whether there is an attack running on it or not 
you can check one or multiple of them and it would select them from that farm list 

Additional context:
Just want to thank you for all the work you do these tools from the old days are hard to find now much apricated

**Comment by adipiciu** [comment]
Added in version 2.23.22. Please check and confirm if it works ok.

**Comment by Drshammasi** [comment]
it is brilliant, the only one missing is the one having a raid running on them there is no check box for them to check them out otherwise brilliant
thanks mate

**Comment by adipiciu** [comment]
> it is brilliant, the only one missing is the one having a raid running on them there is no check box for them to check them out otherwise brilliant thanks mate

The raid in progress icon should appear if there are raids in progress.
