### ISSUE TITLE
Market send divide into deliveries.

### ISSUE THREAD

**Issue by kikuman** [adipiciu/Travian-scripts#56]
![Screenshot 2023-12-24 021028](https://github.com/adipiciu/Travian-scripts/assets/5669436/87cb50cd-161d-4a13-83ce-e0fd2ba609c7)
Would it be possible to add a feature that would divide the needed resources into the selected deliveries when there isn't enough merchants? For example, I need to send 15332 and click 3 deliveries, have it divide 15332 into 3 deliveries = 5111 each.
Thanks in advance!

**Comment by adipiciu** [comment]
Good idea, but it will work only for accounts with gold club. It's a little bit complex and currently I have some problems with the new travian reactjs code. I will first need to find a way to select the deliveries and make the changes propagate in the webpage.

**Comment by kikuman** [comment]
I don't have any coding knowledge but how about just adding 2 buttons? ÷2 and ÷3 and have them divide the values entered in the input boxes.

**Comment by adipiciu** [comment]
Something like this?
![image](https://github.com/adipiciu/Travian-scripts/assets/13155063/3ede34e8-f5fc-43b3-9758-3271f25ee88a)

**Comment by kikuman** [comment]
Perfect!

**Comment by adipiciu** [comment]
Added in 2.23.23
