### ISSUE TITLE
Wave builder doesnt work

### ISSUE THREAD

**Issue by winterwolf** [adipiciu/Travian-scripts#58]
**Script Name**
Travian Wave Builder 2.9

**Server address**
ts8.x1.europe.travian.com

**User script manager**
Violentmonkey

**Operating System**
Manjaro

**Describe the bug**
Doesn't work

**Comment by adipiciu** [comment]
Press F12 in the browser. Go to Console tab and see if there any error appearing when you send the waves.

**Comment by adipiciu** [comment]
Tested in Manjaro with Firefox and Violentmoneky and it works ok.

**Comment by winterwolf** [comment]
> Tested in Manjaro with Firefox and Violentmoneky and it works ok.

No, it doesn't, but never mind. This game sucks anyway. I just removed my account and the problem is solved!
