### ISSUE TITLE
Add new feature

### ISSUE THREAD

**Issue by Dupzzy** [adipiciu/Travian-scripts#6]
I'd be so good if when searching for neighbors we can see if the certain guy / oasis is already being attacked by you, from any village hovering to the attack displaying additional info about the attack like city that you are attacking from, and when is it gonna  arrive and also to have another feature, if the army is returning from an attack from.

Basically having 3 icons

1 When you are attacking the certain guy / oasis
2 For when the army is already returning from there
3 Reinforcements icon

Looking forward to feedback for this suggestion, it would really help me out

**Comment by adipiciu** [comment]
This cannot be done without making hundreds of server requests. Also the crop/neighbors search should be used with caution, as it makes server requests which can result in account ban.

**Comment by Dupzzy** [comment]
I understand, can I ask something else.. in the reports there is extended information on resources lost, but it's not calculating the units that went in the hospital, and when there is a hospital the calculations of the resources lost are wrong.
For example, 50 clubswingers die in attack, but 20 went in the hospital and the script calculates the resources lost for the 30 that didn't go in the hospital, It's really useful for me to know of each resources exactly how much I've lost. Looking forward to your answer

**Comment by adipiciu** [comment]
> I understand, can I ask something else.. in the reports there is extended information on resources lost, but it's not calculating the units that went in the hospital, and when there is a hospital the calculations of the resources lost are wrong. For example, 50 clubswingers die in attack, but 20 went in the hospital and the script calculates the resources lost for the 30 that didn't go in the hospital, It's really useful for me to know of each resources exactly how much I've lost. Looking forward to your answer

Added hospital support in the battle analyzer.
