### ISSUE TITLE
Sending all lists doesnt work well

### ISSUE THREAD

**Issue by TravianPlayer** [adipiciu/Travian-scripts#63]
**Script Name**
Travian Task Queue

**Travian Server address**
All

**Browser**
Example: Chrome

**User script manager**
Tampermonkey

**Operating System**
Windows

**Describe the bug**
When I use (send later) for send all lists button. Instead of clicking that button akone, the script click all farms one by one.
This may look like

**Comment by adipiciu** [comment]
Travian does the same thing. It sends a server request for each farmlist.

**Comment by adipiciu** [comment]
And please censor the coordinates or other elements that can identify the account.

**Comment by TravianPlayer** [comment]
Thanks
I deleted the message
Can't the script imitate the user action.
Just click that button, and let travian do the rest ?

I am afraid that there will be a time different between the script clicking all lists and the send all button
This will be very noticed if there is lag and may lead into ban

Thanks in advance

**Comment by TravianPlayer** [comment]
For example: 
What travian (send all button) does:
- Send list 1 in 00:00:00.00
- Send list 1 in 00:00:00.15
- Send list 1 in 00:00:00.45 

What click one by one does:
- Send list 1 in 00:00:00.00
- Send list 1 in 00:00:00.15
- Send list 1 in 00:00:00.30

This unfirmaty (if exist) will cause troubles to users.
If it possible to make the script hit where (send all button) is.

And if that what it actually does, then you don't need to bother your self with all that :D

Thanks, again.

**Comment by adipiciu** [comment]
You can try with an autoclicker to achieve what you need.

**Comment by adipiciu** [comment]
> Can you add a loop to the sending list button to automate the sending by the interval?

You can do something similar. You can enter a list:

![image](https://github.com/user-attachments/assets/eaf5813f-6fb9-451a-a6a6-763f0f751225)
