### ISSUE TITLE
Resource bar+ > Get Lack Resource from Hero

### ISSUE THREAD

**Issue by iam1412** [adipiciu/Travian-scripts#64]
Feature request:
Resource bar+ > get lack resource from hero. 

Integrate Idea for get lack some resource from hero bag for build now,
Maybe, I want for building now but lack some resource and I'll going to hero bag, then pull resource.

**Comment by adipiciu** [comment]
ResourceBar+ doesn't make any server requests except for the crop/animal finder. I don't want to add more functions that can get the script detected, like it happened with the trade routes automatic creation.

**Comment by iam1412** [comment]
You're Right

**Comment by iam1412** [comment]
Reopen:

Who want for the feature pull resource from hero:
Install from Fork version: https://github.com/iam1412/Travian-scripts
