### ISSUE TITLE
Taask queue bug

### ISSUE THREAD

**Issue by Ometron17** [adipiciu/Travian-scripts#67]
**Travian Task Queue**

**https://ts1.x1.europe.travian.com/**

**Chrome/Chromium**

**Tampermonkey**

**Windows**

**My Task Queue just disappeared **:(

**Comment by adipiciu** [comment]
Probably you have an older version. Try to remove it from Tampermonkey and reinstall it back.

**Comment by adipiciu** [comment]
The send might fail if you don't have a rally point on the active village.

**Comment by Ometron17** [comment]
so maybe i can still set tasks ?? i just dont see them ?

**Comment by adipiciu** [comment]
![image](https://github.com/adipiciu/Travian-scripts/assets/13155063/0e6bfdc8-9091-475e-97b3-5570afe79fc6)
