### ISSUE TITLE
Add oasis to farmlist with simple click and expand oasis scan

### ISSUE THREAD

**Issue by MariusGjerd** [adipiciu/Travian-scripts#69]
**Script Name**
Travian Resource Bar Plus 

**Describe the solution you'd like**
When you search for neighbours when map is opened, it would be nice to be able scan further then 40 fields. Also have icon/text about what kind of oasis it is (clay, iron, wood, crop, 25/25%? 50%? etc). Would be pretty cool to have a single button to add these osasis from the scan into a raid list with a single click or two.

**Describe alternatives you've considered**
Opening map, click on each oasis, then add them to raid list, takes alot of time.

**Comment by MariusGjerd** [comment]
another suggestion would also be that whenever you find and oasis on the oasis scan, there could potentially be a automatic simulator that would tell you how many troops you neeed to send of a unique type, or just attack power.

lets say that you find and oasis with 10 wolves, it will calculate how many troops are neeeded to have minimal casulties, maybe allow to have casulties under a certain precentage

**Comment by adipiciu** [comment]
Added features in version 2.24.8
