### ISSUE TITLE
timers for warehouse/granary needs to be reversed in Arabic Language.

### ISSUE THREAD

**Issue by HewCo** [adipiciu/Travian-scripts#7]
timers for warehouse/granary needs to be reversed in Arabic Language.

![2021-11-09 03_39_51-Travian Tournament 2021 - FINALS — Mozilla Firefox](https://user-images.githubusercontent.com/90363685/140840829-8ffb53c1-e38e-4910-bb65-223ceb5d2cc4.png)

**Comment by adipiciu** [comment]
Hmm, it worked before. Don't know when they moved things. It seems other things are not properly arranged for right to left languages. I will fix it in the next version. Thanks for the info.

**Comment by HewCo** [comment]
Yeah there is few other things too like these 2 buttons covering the villages names

![image](https://user-images.githubusercontent.com/90363685/140942025-a9d713d5-7e86-4812-9cf5-8b2df0f51058.png)

**Comment by adipiciu** [comment]
Fixed in the new script version
