### ISSUE TITLE
Travian Update

### ISSUE THREAD

**Issue by Anife20** [adipiciu/Travian-scripts#72]
**Script Name**
Example: Travian Resource Bar Plus andTravian Task Queue and Travian Wave Builder

Please Update I would like to ask, if possible, for an update for the new travian beta with the new nation vikings.Thanks.

**Comment by adipiciu** [comment]
Hi,
Unfortunately, I don't have an account on the beta server. If you have an account you can share, you can write me on private.

**Comment by adipiciu** [comment]
Or if anyone has an invitation code, please send it in private.

**Comment by Anife20** [comment]
Hello, I will try to get the entry of someone who wants to delete it because it was for invitations. I am also on the server only as dual and I do not have my own account.

**Comment by adipiciu** [comment]
@Anife20 You can send me on skype, telegram. ID: adipiciu
or Discord: 418477003860344834

**Comment by Anife20** [comment]
I sent a request on discord
