### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by Qussayyon** [adipiciu/Travian-scripts#8]
Hi @adipiciu,

I think it would be great to have 2 extra icons in villages list which directly take us to dorf1, and dorf2, in old script (beyond travian 3) we used to have that feature. The feature does not have extra requests to server as these data actually available from village list.
It would be like this:
from village 1 to another village **resources** view:
travian.com/**dorf1**.php?newdid=9616&

from village 1 to another village **buildings** view:
travian.com/**dorf2**.php?newdid=9616&

So it's just repeated link and the difference is: dorf1 or dorf2.

**Comment by adipiciu** [comment]
Do you know where does button where located? Did they had an icon?

**Comment by Qussayyon** [comment]
They had icons, 2 simple but meaningful icons (2 circles), and icons where located before villages' names in villages' list table. I looked for example but I did not find.

**Comment by adipiciu** [comment]
I can add this, but I will need to find some icons.

**Comment by Qussayyon** [comment]
I tried `wayback` machine to find icons from old script, but I did not find so far.
it used to be in any travian Beyond script. specifically this one:
[Travian3 Beyond - ML&CN](https://userscripts-mirror.org/scripts/show/28129)

**Comment by Qussayyon** [comment]
Another feature:
Is it possible to make another script to develop the village automatically?
for example develop resources fields up to level 5 each? let say: I opened `travian.com/build.php?id=1&gid=1` then instead of "– Upgrade later –", it will be: upgrade to level ? then the player can choose the level for that filed.

**Comment by adipiciu** [comment]
> Is it possible to make another script to develop the village automatically?

I don't have time and interest to develop another script.

**Comment by adipiciu** [comment]
The feature was added in the script.

**Comment by Qussayyon** [comment]
Thanks,
Appreciated.
