### ISSUE TITLE
Bug in links

### ISSUE THREAD

**Issue by Qussayyon** [adipiciu/Travian-scripts#9]
Hi @adipiciu,

There is a bug when using script in latest version of travian 4.4
if you are in hero view but not in main view, so you are at:
`travian.com/hero/attributes`, or
`travian.com/hero/attributes`, or
`travian.com/hero/adventures`, or
`travian.com/hero/auction`, but not:
`travian.com/hero`
then you click on any link from links provided by script, then it will not go to desired target. because the link is broken, it become like this:
`travian.com/hero/karte.php?d=71622` . Which keeps you in hero view, I think because it's only cutting last part of URL.

Thanks in advance.

**Comment by adipiciu** [comment]
Hi,

This seems to be a bug in travian. You can see they have the same problem with the links from the village links in the right menu.
The script is just using the travian links it gets from the game.

**Comment by Qussayyon** [comment]
Hi,

You mean the links they have in Travian plus?

I did not try it actually, nonetheless, we can fix it in script.

BTW:
Do you use any specific IDE to help you developing this script?

**Comment by Qussayyon** [comment]
I just tried travian's links system:
As you see in picture, you need put whole link, if it is a link to another village.

![Screenshot 2021-11-16](https://user-images.githubusercontent.com/13088819/141946709-a8357463-2bea-4ff4-8d33-65e5a1714fc8.png)

**Comment by adipiciu** [comment]
I am speaking about the travian village list. It has the same behavior. The script just reads what travian puts in the village list links.
![image](https://user-images.githubusercontent.com/13155063/142423848-5e5c1ed1-2ade-4c01-822f-c9af613a0593.png)

**Comment by Qussayyon** [comment]
I'm talking about the links from (+) feature
![2021-11-19__12-46-15__+0800](https://user-images.githubusercontent.com/13088819/142566538-3786e423-67a9-4b3e-b6ff-288eb3d091d4.png)
:

if you have a link to:
`travian.com/karte.php?d=71622`

It will become:
`travian.com/hero/karte.php?d=71622`

**Comment by adipiciu** [comment]
Ok, I will try to fix the bug in the next version.

**Comment by Qussayyon** [comment]
Thank you very much @adipiciu,

if you do not mind:
Do you use any specific IDE/application to help you developing this script?

**Comment by adipiciu** [comment]
> if you do not mind: Do you use any specific IDE/application to help you developing this script?

Started with Notepad++, now using Visual Code with various extensions.

**Comment by Qussayyon** [comment]
great, is it possible to share the extensions related to developing scripts?  😅

**Comment by adipiciu** [comment]
I don't use any javascript extension, as Visual Code has syntax highlighting by default. Bu there are many extension that you can use, like ESLint for code validation.

**Comment by Qussayyon** [comment]
ok, great, thank you very much.

**Comment by adipiciu** [comment]
Fixed.

**Comment by Qussayyon** [comment]
Thanks.
Appreciated.
